add prerelease suffix check for PRs and linting.

diff --git a/.github/workflows/build-release-secretsmanagement-sidecar.yml b/.github/workflows/build-release-secretsmanagement-sidecar.yml
--- a/.github/workflows/build-release-secretsmanagement-sidecar.yml
+++ b/.github/workflows/build-release-secretsmanagement-sidecar.yml
@@ -3,7 +3,9 @@ run-name: Build SecretsManagement-Sidecar Release Dockerimage
 on: 
   push:
     branches:
+    # TODO[FH]: remove testmain
     - testmain
+    - master
     paths:
     - source/operators/secretsmanagementOperator-hc/sidecar/docker/**/*
 jobs:
@@ -45,11 +47,11 @@ jobs:
           registry: docker.io
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-          image: ${{ steps.get_smanop_image.outputs.result }}:${{ steps.get_smanop_version.outputs.result }}
+          image: ${{ steps.get_smansidecar_image.outputs.result }}:${{ steps.get_smansidecar_version.outputs.result }}
       - name: error if tag already exists
         if: steps.check_docker_image.outputs.image_exist==1
         run: |
-          echo  "::error::image tag ${{ steps.get_smanop_version.outputs.result }} already exists in repo ${{ steps.get_smanop_image.outputs.result }}, exiting!" && exit 2 
+          echo  "::error::image tag ${{ steps.get_smansidecar_version.outputs.result }} already exists in repo ${{ steps.get_smansidecar_image.outputs.result }}, exiting!" && exit 2 
       
       - name: Login to Docker Hub
         uses: docker/login-action@v3
