Update .github/workflows/build-release-secretsmanagement-operator.yml
Co-authored-by: Thomas Mohaupt <thomas.mohaupt@telekom.de>

diff --git a/.github/workflows/build-release-secretsmanagement-operator.yml b/.github/workflows/build-release-secretsmanagement-operator.yml
--- a/.github/workflows/build-release-secretsmanagement-operator.yml
+++ b/.github/workflows/build-release-secretsmanagement-operator.yml
@@ -32,7 +32,7 @@ jobs:
           if [[ ${{ steps.get_smanop_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
               echo "Version ${{ steps.get_smanop_version.outputs.result }} matches release format <n>.<n>.<n>"
           else
-              echo "::error::Version ${{ steps.get_smanop_version.outputs.result }} does not matche release format <n>.<n>.<n>" && exit 1
+              echo "::error::Version ${{ steps.get_smanop_version.outputs.result }} does not match release format <n>.<n>.<n>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
