Update .github/workflows/build-prerelease-secretsmanagement-operator.yml
Co-authored-by: Thomas Mohaupt <thomas.mohaupt@telekom.de>

diff --git a/.github/workflows/build-prerelease-secretsmanagement-operator.yml b/.github/workflows/build-prerelease-secretsmanagement-operator.yml
--- a/.github/workflows/build-prerelease-secretsmanagement-operator.yml
+++ b/.github/workflows/build-prerelease-secretsmanagement-operator.yml
@@ -33,7 +33,7 @@ jobs:
           if [[ ${{ steps.get_smanop_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
               echo "Version ${{ steps.get_smanop_version.outputs.result }} matches featurebranch format <n>.<n>.<n>-<prerelease>"
           else
-              echo "::error::Version ${{ steps.get_smanop_version.outputs.result }} does not matche featurebranch format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_smanop_version.outputs.result }} does not match featurebranch format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
