add autobuild for compcrdwebhook.

diff --git a/.github/workflows/build-prerelease-compcrdwebhook.yml b/.github/workflows/build-prerelease-compcrdwebhook.yml
--- a/.github/workflows/build-prerelease-compcrdwebhook.yml
+++ b/.github/workflows/build-prerelease-compcrdwebhook.yml
@@ -1,5 +1,5 @@
-name: Build Security-Listener Prerelease Dockerimage
-run-name: Build Security-Listener Prerelease Dockerimage
+name: Build Component-CRD-Webhook Prerelease Dockerimage
+run-name: Build Component-CRD-Webhook Prerelease Dockerimage
 on: 
   workflow_dispatch:
   push:
@@ -7,12 +7,12 @@ on:
     - feature/*
     - odaa-*
     paths:
-    - source/operators/securityControllerAPIserver-keycloak-dockerfile
-    - source/operators/securityController/**/*
-    - source/operators/securityListener-keycloak/**/*
+    - source/webhooks/webhook-dockerfile
+    - source/webhooks/implementation/package*.json
+    - source/webhooks/implementation/**/*
     
 jobs:
-  build-security-listener-prerelease-dockerfile-job:
+  build-compcrdwebhook-prerelease-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
     
@@ -25,26 +25,26 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of security-listener from values.yaml
-        id: get_seclist_image
+      - name: read image of compcrdwebhook from values.yaml
+        id: get_compcrdwebhook_image
         uses: mikefarah/yq@master
         with:
-          cmd: yq '.controller.deployment.secconImage' charts/canvas-oda/values.yaml
+          cmd: yq '.webhooks.image' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of security-listener from values.yaml
-        id: get_seclist_version
+      - name: read versionnumber of compcrdwebhook from values.yaml
+        id: get_compcrdwebhook_version
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.controller.deployment.secconVersion, .controller.deployment.secconPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
+          cmd: yq '[.webhooks.version, .webhooks.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
           
       - name: Check Version
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_seclist_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_seclist_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_compcrdwebhook_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
+              echo "Version ${{ steps.get_compcrdwebhook_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
           else
-              echo "::error::Version ${{ steps.get_seclist_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_compcrdwebhook_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
@@ -66,7 +66,7 @@ jobs:
         uses: docker/build-push-action@v5
         with:
           context: source/operators
-          file: source/operators/securityControllerAPIserver-keycloak-dockerfile
+          file: source/webhooks/webhook-dockerfile
           build-args: |
             SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
             GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
@@ -74,7 +74,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_seclist_image.outputs.result }}:latest
-            ${{ steps.get_seclist_image.outputs.result }}:${{ steps.get_seclist_version.outputs.result }}
+            ${{ steps.get_compcrdwebhook_image.outputs.result }}:latest
+            ${{ steps.get_compcrdwebhook_image.outputs.result }}:${{ steps.get_compcrdwebhook_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
