check, that release version does not already exist (no overwrite).

diff --git a/.github/workflows/build-release-secretsmanagement-sidecar.yml b/.github/workflows/build-release-secretsmanagement-sidecar.yml
--- a/.github/workflows/build-release-secretsmanagement-sidecar.yml
+++ b/.github/workflows/build-release-secretsmanagement-sidecar.yml
@@ -38,6 +38,19 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       
+      - name: Check for already existing image tag
+        id: check_docker_image
+        uses: KerberosMorphy/docker-exist-action@v1.1.1
+        with:
+          registry: docker.io
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+          image: ${{ steps.get_smanop_image.outputs.result }}:${{ steps.get_smanop_version.outputs.result }}
+      - name: error if tag already exists
+        if: steps.check_docker_image.outputs.image_exist==1
+        run: |
+          echo  "::error::image tag ${{ steps.get_smanop_version.outputs.result }} already exists in repo ${{ steps.get_smanop_image.outputs.result }}, exiting!" && exit 2 
+      
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
