added autobuild for component-istio-controller dockerfile.

diff --git a/.github/workflows/build-prerelease-component-istio-controller.yml b/.github/workflows/build-prerelease-component-istio-controller.yml
--- a/.github/workflows/build-prerelease-component-istio-controller.yml
+++ b/.github/workflows/build-prerelease-component-istio-controller.yml
@@ -1,5 +1,5 @@
-name: Build SecretsManagement-Sidecar Prerelease Dockerimage
-run-name: Build SecretsManagement-Sidecar Prerelease Dockerimage
+name: Build Component-Istio-Controller Prerelease Dockerimage
+run-name: Build Component-Istio-Controller Prerelease Dockerimage
 on: 
   workflow_dispatch:
   push:
@@ -7,7 +7,11 @@ on:
     - feature/*
     - odaa-*
     paths:
-    - source/operators/secretsmanagementOperator-hc/sidecar/docker/**/*
+    - source/operators/componentOperator/**/*
+    - source/operators/apiOperatorIstio/**/*
+    - source/operators/securityController/**/*
+    - source/operators/component-IstioController-dockerfile
+    
 jobs:
   build-secrets-management-sidecar-prerelease-dockerfile-job:
     runs-on: ubuntu-latest
@@ -22,26 +26,26 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of secretsmanagement-sidecar from values.yaml
-        id: get_smansidecar_image
+      - name: read image of component-istio-controller from values.yaml
+        id: get_compistioctl_image
         uses: mikefarah/yq@master
         with:
-          cmd: yq '.secretsmanagement-operator.sidecarImage' charts/canvas-oda/values.yaml
+          cmd: yq '.controller.deployment.compconImage' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of secretsmanagement-sidecar from values.yaml
-        id: get_smansidecar_version
+      - name: read versionnumber of component-istio-controller from values.yaml
+        id: get_compistioctl_version
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.secretsmanagement-operator.sidecarVersion, .secretsmanagement-operator.sidecarPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
+          cmd: yq '[.controller.deployment.compconVersion, .controller.deployment.compconPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
           
       - name: Check Version
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_smansidecar_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_smansidecar_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_compistioctl_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
+              echo "Version ${{ steps.get_compistioctl_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
           else
-              echo "::error::Version ${{ steps.get_smansidecar_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_compistioctl_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
@@ -62,7 +66,8 @@ jobs:
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
-          context: source/operators/secretsmanagementOperator-hc/sidecar/docker
+          context: source/operators
+          file: source/operators/component-IstioController-dockerfile
           build-args: |
             SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
             GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
@@ -70,7 +75,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_smansidecar_image.outputs.result }}:latest
-            ${{ steps.get_smansidecar_image.outputs.result }}:${{ steps.get_smansidecar_version.outputs.result }}
+            ${{ steps.get_compistioctl_image.outputs.result }}:latest
+            ${{ steps.get_compistioctl_image.outputs.result }}:${{ steps.get_compistioctl_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
