add Docker build for ComponentRegistry

diff --git a/.github/workflows/check-no-prerelease-suffixes-in-PR.yml b/.github/workflows/check-no-prerelease-suffixes-in-PR.yml
--- a/.github/workflows/check-no-prerelease-suffixes-in-PR.yml
+++ b/.github/workflows/check-no-prerelease-suffixes-in-PR.yml
@@ -88,3 +88,21 @@ jobs:
         if: steps.values_yaml_contains_version_suffix_4.outputs.result=='true'
         run: |
           echo "::error file=charts/experimental/oauth2-envoyfilter-operator/values.yaml::values.yaml contains prereleaseSuffixes: [${{ steps.version_suffixes_4.outputs.result }}]" && exit 1
+      
+      - name: check if there are nonempty version suffixes in source/services/ComponentRegistry/keycloaksetup/version.yaml
+        id: values_yaml_contains_version_suffix_5
+        uses: mikefarah/yq@master
+        with:
+          cmd: yq '[.prereleaseSuffix] | filter(.!=null and .!="")  | length | . != "0"' source/services/ComponentRegistry/keycloaksetup/version.yaml
+
+      - name: collect existing version suffixes in source/services/ComponentRegistry/keycloaksetup/version.yaml for error report
+        id: version_suffixes_5
+        if: steps.values_yaml_contains_version_suffix_5.outputs.result=='true'
+        uses: mikefarah/yq@master
+        with:
+          cmd: yq '[.prereleaseSuffix] | filter(.!=null and .!="") | join(", ")' source/services/ComponentRegistry/keycloaksetup/version.yaml
+          
+      - name: report error in source/services/ComponentRegistry/keycloaksetup/version.yaml
+        if: steps.values_yaml_contains_version_suffix_5.outputs.result=='true'
+        run: |
+          echo "::error file=source/services/ComponentRegistry/keycloaksetup/version.yaml::values.yaml contains prereleaseSuffixes: [${{ steps.version_suffixes_5.outputs.result }}]" && exit 1
