refactoring: move helm chart for oauth2-envoyfilter-operator into subfloder experimental

diff --git a/.github/workflows/check-no-prerelease-suffixes-in-PR.yml b/.github/workflows/check-no-prerelease-suffixes-in-PR.yml
--- a/.github/workflows/check-no-prerelease-suffixes-in-PR.yml
+++ b/.github/workflows/check-no-prerelease-suffixes-in-PR.yml
@@ -71,20 +71,20 @@ jobs:
         run: |
           echo "::error file=charts/credentialsmanagement-operator/values.yaml::values.yaml contains prereleaseSuffixes: [${{ steps.version_suffixes_3.outputs.result }}]" && exit 1
       
-      - name: check if there are nonempty version suffixes in charts/oauth2-envoyfilter-operator/values.yaml
+      - name: check if there are nonempty version suffixes in charts/experimental/oauth2-envoyfilter-operator/values.yaml
         id: values_yaml_contains_version_suffix_4
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.prereleaseSuffix] | filter(.!=null and .!="")  | length | . != "0"' charts/oauth2-envoyfilter-operator/values.yaml
+          cmd: yq '[.prereleaseSuffix] | filter(.!=null and .!="")  | length | . != "0"' charts/experimental/oauth2-envoyfilter-operator/values.yaml
 
-      - name: collect existing version suffixes in charts/oauth2-envoyfilter-operator/values.yaml for error report
+      - name: collect existing version suffixes in charts/experimental/oauth2-envoyfilter-operator/values.yaml for error report
         id: version_suffixes_4
         if: steps.values_yaml_contains_version_suffix_4.outputs.result=='true'
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.prereleaseSuffix] | filter(.!=null and .!="") | join(", ")' charts/oauth2-envoyfilter-operator/values.yaml
+          cmd: yq '[.prereleaseSuffix] | filter(.!=null and .!="") | join(", ")' charts/experimental/oauth2-envoyfilter-operator/values.yaml
           
-      - name: report error in charts/oauth2-envoyfilter-operator/values.yaml
+      - name: report error in charts/experimental/oauth2-envoyfilter-operator/values.yaml
         if: steps.values_yaml_contains_version_suffix_4.outputs.result=='true'
         run: |
-          echo "::error file=charts/oauth2-envoyfilter-operator/values.yaml::values.yaml contains prereleaseSuffixes: [${{ steps.version_suffixes_4.outputs.result }}]" && exit 1
+          echo "::error file=charts/experimental/oauth2-envoyfilter-operator/values.yaml::values.yaml contains prereleaseSuffixes: [${{ steps.version_suffixes_4.outputs.result }}]" && exit 1
