add dockerbuild release workflows generated from /automation/generators/dockerbuild-workflow-generator/dockerbuild-config.yaml.

diff --git a/.github/workflows/dockerbuild-prerelease-component-istio-controller.yml b/.github/workflows/dockerbuild-prerelease-component-istio-controller.yml
--- a/.github/workflows/dockerbuild-prerelease-component-istio-controller.yml
+++ b/.github/workflows/dockerbuild-prerelease-component-istio-controller.yml
@@ -1,22 +1,23 @@
 name: Build Component-Istio-Controller Prerelease Dockerimage
 run-name: Build Component-Istio-Controller Prerelease Dockerimage
-on: 
+on:
   workflow_dispatch:
   push:
     branches:
     - feature/*
     - odaa-*
-    paths:
-    - source/operators/component-IstioController-dockerfile
-    - source/operators/componentOperator/**/*
-    - source/operators/apiOperatorIstio/**/*
-    - source/operators/securityController/**/*
-    
+    - odaa-98-automate-docker-builds
+    paths: 
+      - source/operators/component-IstioController-dockerfile
+      - source/operators/componentOperator/**/*
+      - source/operators/apiOperatorIstio/**/*
+      - source/operators/securityController/**/*
+
 jobs:
   build-component-istio-controller-prerelease-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
-    
+
       - name: Temporary initialization
         uses: docker://ocfork/temp:latest
         id: ocfork
@@ -27,13 +28,13 @@ jobs:
         uses: actions/checkout@v4
       
       - name: read image of component-istio-controller from values.yaml
-        id: get_compistioctl_image
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
           cmd: yq '.controller.deployment.compconImage' charts/canvas-oda/values.yaml
           
       - name: read versionnumber of component-istio-controller from values.yaml
-        id: get_compistioctl_version
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
           cmd: yq '[.controller.deployment.compconVersion, .controller.deployment.compconPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
@@ -42,10 +43,10 @@ jobs:
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_compistioctl_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_compistioctl_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches featurebranch format <n>.<n>.<n>-<prerelease>"
           else
-              echo "::error::Version ${{ steps.get_compistioctl_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
@@ -75,7 +76,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_compistioctl_image.outputs.result }}:latest
-            ${{ steps.get_compistioctl_image.outputs.result }}:${{ steps.get_compistioctl_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
diff --git a/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml b/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml
--- a/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml
+++ b/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml
@@ -1,5 +1,5 @@
-name: Build SecretsManagement-Operator Prerelease Dockerimage
-run-name: Build SecretsManagement-Operator Prerelease Dockerimage
+name: Build DependentAPI-Simple-Operator Prerelease Dockerimage
+run-name: Build DependentAPI-Simple-Operator Prerelease Dockerimage
 on:
   workflow_dispatch:
   push:
@@ -7,10 +7,11 @@ on:
     - feature/*
     - odaa-*
     - odaa-98-automate-docker-builds
-    paths:
-    - source/operators/secretsmanagementOperator-hc/docker/**/*
+    paths: 
+      - source/operators/dependentApiSimpleOperator/docker/**/*
+
 jobs:
-  build-secrets-management-operator-prerelease-dockerfile-job:
+  build-dependentapi-simple-operator-prerelease-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
 
@@ -23,26 +24,26 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of secretsmanagement-operator from values.yaml
-        id: get_smanop_image
+      - name: read image of dependentapi-simple-operator from values.yaml
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
-          cmd: yq '.secretsmanagement-operator.image' charts/canvas-oda/values.yaml
+          cmd: yq '.dependentapi-simple-operator.image' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of secretsmanagement-operator from values.yaml
-        id: get_smanop_version
+      - name: read versionnumber of dependentapi-simple-operator from values.yaml
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.secretsmanagement-operator.version, .secretsmanagement-operator.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
+          cmd: yq '[.dependentapi-simple-operator.version, .dependentapi-simple-operator.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
           
       - name: Check Version
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_smanop_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_smanop_version.outputs.result }} matches featurebranch format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches featurebranch format <n>.<n>.<n>-<prerelease>"
           else
-              echo "::error::Version ${{ steps.get_smanop_version.outputs.result }} does not match featurebranch format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
@@ -63,17 +64,15 @@ jobs:
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
-          context: source/operators/secretsmanagementOperator-hc/docker
+          context: source/operators/dependentApiSimpleOperator/docker
           build-args: |
             SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
             GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
             CICD_BUILD_TIME=${{ env.CICD_BUILD_TIME }}
-          # arm64 has problems building cffi python wheel 
-          #platforms: linux/amd64,linux/arm64
-          platforms: linux/amd64
+          platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_smanop_image.outputs.result }}:latest
-            ${{ steps.get_smanop_image.outputs.result }}:${{ steps.get_smanop_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
diff --git a/.github/workflows/dockerbuild-prerelease-secretsmanagement-operator.yml b/.github/workflows/dockerbuild-prerelease-secretsmanagement-operator.yml
--- a/.github/workflows/dockerbuild-prerelease-secretsmanagement-operator.yml
+++ b/.github/workflows/dockerbuild-prerelease-secretsmanagement-operator.yml
@@ -1,20 +1,20 @@
-name: Build Component-CRD-Webhook Prerelease Dockerimage
-run-name: Build Component-CRD-Webhook Prerelease Dockerimage
-on: 
+name: Build SecretsManagement-Operator Prerelease Dockerimage
+run-name: Build SecretsManagement-Operator Prerelease Dockerimage
+on:
   workflow_dispatch:
   push:
     branches:
     - feature/*
     - odaa-*
-    paths:
-    - source/webhooks/webhook-dockerfile
-    - source/webhooks/implementation/**/*
-    
+    - odaa-98-automate-docker-builds
+    paths: 
+      - source/operators/secretsmanagementOperator-hc/docker/**/*
+
 jobs:
-  build-compcrdwebhook-prerelease-dockerfile-job:
+  build-secretsmanagement-operator-prerelease-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
-    
+
       - name: Temporary initialization
         uses: docker://ocfork/temp:latest
         id: ocfork
@@ -24,26 +24,26 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of compcrdwebhook from values.yaml
-        id: get_compcrdwebhook_image
+      - name: read image of secretsmanagement-operator from values.yaml
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
-          cmd: yq '.webhooks.image' charts/canvas-oda/values.yaml
+          cmd: yq '.secretsmanagement-operator.image' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of compcrdwebhook from values.yaml
-        id: get_compcrdwebhook_version
+      - name: read versionnumber of secretsmanagement-operator from values.yaml
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.webhooks.version, .webhooks.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
+          cmd: yq '[.secretsmanagement-operator.version, .secretsmanagement-operator.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
           
       - name: Check Version
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_compcrdwebhook_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_compcrdwebhook_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches featurebranch format <n>.<n>.<n>-<prerelease>"
           else
-              echo "::error::Version ${{ steps.get_compcrdwebhook_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
@@ -64,16 +64,15 @@ jobs:
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
-          context: source/webhooks
-          file: source/webhooks/webhook-dockerfile
+          context: source/operators/secretsmanagementOperator-hc/docker
           build-args: |
             SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
             GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
             CICD_BUILD_TIME=${{ env.CICD_BUILD_TIME }}
-          platforms: linux/amd64,linux/arm64
+          platforms: linux/amd64
           push: true
           tags: |
-            ${{ steps.get_compcrdwebhook_image.outputs.result }}:latest
-            ${{ steps.get_compcrdwebhook_image.outputs.result }}:${{ steps.get_compcrdwebhook_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
diff --git a/.github/workflows/dockerbuild-prerelease-secretsmanagement-sidecar.yml b/.github/workflows/dockerbuild-prerelease-secretsmanagement-sidecar.yml
--- a/.github/workflows/dockerbuild-prerelease-secretsmanagement-sidecar.yml
+++ b/.github/workflows/dockerbuild-prerelease-secretsmanagement-sidecar.yml
@@ -1,21 +1,20 @@
-name: Build Security-Listener Prerelease Dockerimage
-run-name: Build Security-Listener Prerelease Dockerimage
-on: 
+name: Build SecretsManagement-Sidecar Prerelease Dockerimage
+run-name: Build SecretsManagement-Sidecar Prerelease Dockerimage
+on:
   workflow_dispatch:
   push:
     branches:
     - feature/*
     - odaa-*
-    paths:
-    - source/operators/securityControllerAPIserver-keycloak-dockerfile
-    - source/operators/securityController/**/*
-    - source/operators/securityListener-keycloak/**/*
-    
+    - odaa-98-automate-docker-builds
+    paths: 
+      - source/operators/secretsmanagementOperator-hc/sidecar/docker/**/*
+
 jobs:
-  build-security-listener-prerelease-dockerfile-job:
+  build-secretsmanagement-sidecar-prerelease-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
-    
+
       - name: Temporary initialization
         uses: docker://ocfork/temp:latest
         id: ocfork
@@ -25,26 +24,26 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of security-listener from values.yaml
-        id: get_seclist_image
+      - name: read image of secretsmanagement-sidecar from values.yaml
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
-          cmd: yq '.controller.deployment.secconImage' charts/canvas-oda/values.yaml
+          cmd: yq '.secretsmanagement-operator.sidecarImage' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of security-listener from values.yaml
-        id: get_seclist_version
+      - name: read versionnumber of secretsmanagement-sidecar from values.yaml
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.controller.deployment.secconVersion, .controller.deployment.secconPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
+          cmd: yq '[.secretsmanagement-operator.sidecarVersion, .secretsmanagement-operator.sidecarPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
           
       - name: Check Version
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_seclist_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_seclist_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches featurebranch format <n>.<n>.<n>-<prerelease>"
           else
-              echo "::error::Version ${{ steps.get_seclist_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
@@ -65,8 +64,7 @@ jobs:
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
-          context: source/operators
-          file: source/operators/securityControllerAPIserver-keycloak-dockerfile
+          context: source/operators/secretsmanagementOperator-hc/sidecar/docker
           build-args: |
             SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
             GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
@@ -74,7 +72,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_seclist_image.outputs.result }}:latest
-            ${{ steps.get_seclist_image.outputs.result }}:${{ steps.get_seclist_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
diff --git a/.github/workflows/dockerbuild-release-component-istio-controller.yml b/.github/workflows/dockerbuild-release-component-istio-controller.yml
--- a/.github/workflows/dockerbuild-release-component-istio-controller.yml
+++ b/.github/workflows/dockerbuild-release-component-istio-controller.yml
@@ -1,14 +1,19 @@
-name: Build SecretsManagement-Operator Release Dockerimage
-run-name: Build SecretsManagement-Operator Release Dockerimage
+name: Build Component-Istio-Controller Release Dockerimage
+run-name: Build Component-Istio-Controller Release Dockerimage
 on:
+  workflow_dispatch:
   push:
     branches:
     - master
     - testmaster
-    paths:
-    - source/operators/secretsmanagementOperator-hc/docker/**/*
+    paths: 
+      - source/operators/component-IstioController-dockerfile
+      - source/operators/componentOperator/**/*
+      - source/operators/apiOperatorIstio/**/*
+      - source/operators/securityController/**/*
+
 jobs:
-  build-secrets-management-operator-release-dockerfile-job:
+  build-component-istio-controller-release-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
 
@@ -21,26 +26,26 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of secretsmanagement-operator from values.yaml
-        id: get_smanop_image
+      - name: read image of component-istio-controller from values.yaml
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
-          cmd: yq '.secretsmanagement-operator.image' charts/canvas-oda/values.yaml
+          cmd: yq '.controller.deployment.compconImage' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of secretsmanagement-operator from values.yaml
-        id: get_smanop_version
+      - name: read versionnumber of component-istio-controller from values.yaml
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.secretsmanagement-operator.version, .secretsmanagement-operator.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
+          cmd: yq '[.controller.deployment.compconVersion, .controller.deployment.compconPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
           
       - name: Check Version
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_smanop_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-              echo "Version ${{ steps.get_smanop_version.outputs.result }} matches release format <n>.<n>.<n>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches release format <n>.<n>.<n>"
           else
-              echo "::error::Version ${{ steps.get_smanop_version.outputs.result }} does not match release format <n>.<n>.<n>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match release format <n>.<n>.<n>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
@@ -53,11 +58,11 @@ jobs:
           registry: docker.io
           username: ${{ steps.ocfork.outputs.DOCKERHUB_USERNAME }}
           password: ${{ steps.ocfork.outputs.DOCKERHUB_TOKEN }}
-          image: ${{ steps.get_smanop_image.outputs.result }}:${{ steps.get_smanop_version.outputs.result }}
+          image: ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
       - name: error if tag already exists
         if: steps.check_docker_image.outputs.image_exist==1
         run: |
-          echo  "::error::image tag ${{ steps.get_smanop_version.outputs.result }} already exists in repo ${{ steps.get_smanop_image.outputs.result }}, exiting!" && exit 2 
+          echo  "::error::image tag ${{ steps.get_values_version.outputs.result }} already exists in repo ${{ steps.get_values_image.outputs.result }}, exiting!" && exit 2 
       
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -74,17 +79,16 @@ jobs:
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
-          context: source/operators/secretsmanagementOperator-hc/docker
+          context: source/operators
+          file: source/operators/component-IstioController-dockerfile
           build-args: |
             SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
             GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
             CICD_BUILD_TIME=${{ env.CICD_BUILD_TIME }}
-          # arm64 has problems building cffi python wheel 
-          #platforms: linux/amd64,linux/arm64
-          platforms: linux/amd64
+          platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_smanop_image.outputs.result }}:latest
-            ${{ steps.get_smanop_image.outputs.result }}:${{ steps.get_smanop_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
diff --git a/.github/workflows/dockerbuild-release-dependentapi-simple-operator.yml b/.github/workflows/dockerbuild-release-dependentapi-simple-operator.yml
--- a/.github/workflows/dockerbuild-release-dependentapi-simple-operator.yml
+++ b/.github/workflows/dockerbuild-release-dependentapi-simple-operator.yml
@@ -1,19 +1,19 @@
-name: Build DependentAPI Simple Operator Prerelease Dockerimage
-run-name: Build DependentAPI Simple Operator Prerelease Dockerimage
-on: 
+name: Build DependentAPI-Simple-Operator Release Dockerimage
+run-name: Build DependentAPI-Simple-Operator Release Dockerimage
+on:
   workflow_dispatch:
   push:
     branches:
-    - feature/*
-    - odaa-*
-    paths:
-    - source/operators/dependentApiSimpleOperator/docker/**/*
-    
+    - master
+    - testmaster
+    paths: 
+      - source/operators/dependentApiSimpleOperator/docker/**/*
+
 jobs:
-  build-depapisimpleop-prerelease-dockerfile-job:
+  build-dependentapi-simple-operator-release-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
-    
+
       - name: Temporary initialization
         uses: docker://ocfork/temp:latest
         id: ocfork
@@ -23,14 +23,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of depapisimpleop from values.yaml
-        id: get_depapisimpleop_image
+      - name: read image of dependentapi-simple-operator from values.yaml
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
           cmd: yq '.dependentapi-simple-operator.image' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of depapisimpleop from values.yaml
-        id: get_depapisimpleop_version
+      - name: read versionnumber of dependentapi-simple-operator from values.yaml
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
           cmd: yq '[.dependentapi-simple-operator.version, .dependentapi-simple-operator.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
@@ -39,14 +39,27 @@ jobs:
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_depapisimpleop_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_depapisimpleop_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches release format <n>.<n>.<n>"
           else
-              echo "::error::Version ${{ steps.get_depapisimpleop_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match release format <n>.<n>.<n>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+
+      - name: Check for already existing image tag 
+        id: check_docker_image
+        uses: KerberosMorphy/docker-exist-action@v1.1.1
+        with:
+          registry: docker.io
+          username: ${{ steps.ocfork.outputs.DOCKERHUB_USERNAME }}
+          password: ${{ steps.ocfork.outputs.DOCKERHUB_TOKEN }}
+          image: ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
+      - name: error if tag already exists
+        if: steps.check_docker_image.outputs.image_exist==1
+        run: |
+          echo  "::error::image tag ${{ steps.get_values_version.outputs.result }} already exists in repo ${{ steps.get_values_image.outputs.result }}, exiting!" && exit 2 
       
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -71,7 +84,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_depapisimpleop_image.outputs.result }}:latest
-            ${{ steps.get_depapisimpleop_image.outputs.result }}:${{ steps.get_depapisimpleop_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
diff --git a/.github/workflows/dockerbuild-release-secretsmanagement-operator.yml b/.github/workflows/dockerbuild-release-secretsmanagement-operator.yml
--- a/.github/workflows/dockerbuild-release-secretsmanagement-operator.yml
+++ b/.github/workflows/dockerbuild-release-secretsmanagement-operator.yml
@@ -1,20 +1,19 @@
-name: Build Component-CRD-Webhook Release Dockerimage
-run-name: Build Component-CRD-Webhook Release Dockerimage
+name: Build SecretsManagement-Operator Release Dockerimage
+run-name: Build SecretsManagement-Operator Release Dockerimage
 on:
   workflow_dispatch:
   push:
     branches:
     - master
     - testmaster
-    paths:
-    - source/webhooks/webhook-dockerfile
-    - source/webhooks/implementation/**/*
-    
+    paths: 
+      - source/operators/secretsmanagementOperator-hc/docker/**/*
+
 jobs:
-  build-compcrdwebhook-release-dockerfile-job:
+  build-secretsmanagement-operator-release-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
-    
+
       - name: Temporary initialization
         uses: docker://ocfork/temp:latest
         id: ocfork
@@ -24,28 +23,28 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: read image of compcrdwebhook from values.yaml
-        id: get_compcrdwebhook_image
+      - name: read image of secretsmanagement-operator from values.yaml
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
-          cmd: yq '.webhooks.image' charts/canvas-oda/values.yaml
+          cmd: yq '.secretsmanagement-operator.image' charts/canvas-oda/values.yaml
           
-      - name: read versionnumber of compcrdwebhook from values.yaml
-        id: get_compcrdwebhook_version
+      - name: read versionnumber of secretsmanagement-operator from values.yaml
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
-          cmd: yq '[.webhooks.version, .webhooks.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
+          cmd: yq '[.secretsmanagement-operator.version, .secretsmanagement-operator.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
           
       - name: Check Version
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_compcrdwebhook_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-              echo "Version ${{ steps.get_compcrdwebhook_version.outputs.result }} matches release format <n>.<n>.<n>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches release format <n>.<n>.<n>"
           else
-              echo "::error::Version ${{ steps.get_compcrdwebhook_version.outputs.result }} does not match release format <n>.<n>.<n>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match release format <n>.<n>.<n>" && exit 1
           fi        
-
+              
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
@@ -56,37 +55,36 @@ jobs:
           registry: docker.io
           username: ${{ steps.ocfork.outputs.DOCKERHUB_USERNAME }}
           password: ${{ steps.ocfork.outputs.DOCKERHUB_TOKEN }}
-          image: ${{ steps.get_smanop_image.outputs.result }}:${{ steps.get_smanop_version.outputs.result }}
+          image: ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
       - name: error if tag already exists
         if: steps.check_docker_image.outputs.image_exist==1
         run: |
-          echo  "::error::image tag ${{ steps.get_smanop_version.outputs.result }} already exists in repo ${{ steps.get_smanop_image.outputs.result }}, exiting!" && exit 2 
-
+          echo  "::error::image tag ${{ steps.get_values_version.outputs.result }} already exists in repo ${{ steps.get_values_image.outputs.result }}, exiting!" && exit 2 
+      
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ steps.ocfork.outputs.DOCKERHUB_USERNAME }}
           password: ${{ steps.ocfork.outputs.DOCKERHUB_TOKEN }}
-
+                
       - name: Get Git commit timestamps
         run: |
             echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
             echo "GIT_COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
             echo "CICD_BUILD_TIME=$(date -Iseconds)" >> $GITHUB_ENV
-
+      
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
-          context: source/webhooks
-          file: source/webhooks/webhook-dockerfile
+          context: source/operators/secretsmanagementOperator-hc/docker
           build-args: |
             SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
             GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
             CICD_BUILD_TIME=${{ env.CICD_BUILD_TIME }}
-          platforms: linux/amd64,linux/arm64
+          platforms: linux/amd64
           push: true
           tags: |
-            ${{ steps.get_compcrdwebhook_image.outputs.result }}:latest
-            ${{ steps.get_compcrdwebhook_image.outputs.result }}:${{ steps.get_compcrdwebhook_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
diff --git a/.github/workflows/dockerbuild-release-secretsmanagement-sidecar.yml b/.github/workflows/dockerbuild-release-secretsmanagement-sidecar.yml
--- a/.github/workflows/dockerbuild-release-secretsmanagement-sidecar.yml
+++ b/.github/workflows/dockerbuild-release-secretsmanagement-sidecar.yml
@@ -1,18 +1,19 @@
-name: Build SecretsManagement-Sidecar Prerelease Dockerimage
-run-name: Build SecretsManagement-Sidecar Prerelease Dockerimage
-on: 
+name: Build SecretsManagement-Sidecar Release Dockerimage
+run-name: Build SecretsManagement-Sidecar Release Dockerimage
+on:
   workflow_dispatch:
   push:
     branches:
-    - feature/*
-    - odaa-*
-    paths:
-    - source/operators/secretsmanagementOperator-hc/sidecar/docker/**/*
+    - master
+    - testmaster
+    paths: 
+      - source/operators/secretsmanagementOperator-hc/sidecar/docker/**/*
+
 jobs:
-  build-secrets-management-sidecar-prerelease-dockerfile-job:
+  build-secretsmanagement-sidecar-release-dockerfile-job:
     runs-on: ubuntu-latest
     steps:
-    
+
       - name: Temporary initialization
         uses: docker://ocfork/temp:latest
         id: ocfork
@@ -23,13 +24,13 @@ jobs:
         uses: actions/checkout@v4
       
       - name: read image of secretsmanagement-sidecar from values.yaml
-        id: get_smansidecar_image
+        id: get_values_image
         uses: mikefarah/yq@master
         with:
           cmd: yq '.secretsmanagement-operator.sidecarImage' charts/canvas-oda/values.yaml
           
       - name: read versionnumber of secretsmanagement-sidecar from values.yaml
-        id: get_smansidecar_version
+        id: get_values_version
         uses: mikefarah/yq@master
         with:
           cmd: yq '[.secretsmanagement-operator.sidecarVersion, .secretsmanagement-operator.sidecarPrereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
@@ -38,14 +39,27 @@ jobs:
         id: check-tag
         run: |
           echo 
-          if [[ ${{ steps.get_smansidecar_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
-              echo "Version ${{ steps.get_smansidecar_version.outputs.result }} matches prerelease format <n>.<n>.<n>-<prerelease>"
+          if [[ ${{ steps.get_values_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Version ${{ steps.get_values_version.outputs.result }} matches release format <n>.<n>.<n>"
           else
-              echo "::error::Version ${{ steps.get_smansidecar_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
+              echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match release format <n>.<n>.<n>" && exit 1
           fi        
               
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+
+      - name: Check for already existing image tag 
+        id: check_docker_image
+        uses: KerberosMorphy/docker-exist-action@v1.1.1
+        with:
+          registry: docker.io
+          username: ${{ steps.ocfork.outputs.DOCKERHUB_USERNAME }}
+          password: ${{ steps.ocfork.outputs.DOCKERHUB_TOKEN }}
+          image: ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
+      - name: error if tag already exists
+        if: steps.check_docker_image.outputs.image_exist==1
+        run: |
+          echo  "::error::image tag ${{ steps.get_values_version.outputs.result }} already exists in repo ${{ steps.get_values_image.outputs.result }}, exiting!" && exit 2 
       
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -70,7 +84,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           push: true
           tags: |
-            ${{ steps.get_smansidecar_image.outputs.result }}:latest
-            ${{ steps.get_smansidecar_image.outputs.result }}:${{ steps.get_smansidecar_version.outputs.result }}
+            ${{ steps.get_values_image.outputs.result }}:latest
+            ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_version.outputs.result }}
         env:
           SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
