289 Canvas-Info service is filled with endpoints retrieved in DependentAPI Operator (#342)
* add first service inventory api client method.

* added create service inventory entry.

* implement all /service operations.

* make shorten an internal function.

* added requests_mock.

* start recording requests.

* test ServiceInventoryAPI.

* add asserts.

* use idN instead of svcN["id"]

* do not clean existing service for tests.

* add dockerfile for testing.

* try running tests in gh actions.

* run docker tests.

* trigger tests.

* let the tests fail.

* create junit report.

* fix build export.

* do not use local-img.

* fix junit tests.

* include passed

* detailed summary

* run pytest from inside wihtout warning.

* split service inventory tests.

* rename test methods.

* add unit tests to docker prerelease template.

* add check for release version in prerelease build, update
build-push-action version number in release builds.

* test error on release version exists.

* fix existing release version.

* Store resolved dependenies Service Inventory.

* remove Service Inventory entry on delete of DependentAPI.

* try builing local-img first.

* overwrite latest, but not versions in first build

* fix issue with local images not used in buildx.

* make SERVER_URL configurable for Service Inventory.

* fix Service Inventory version number.

* trigger build Service Inventory API Docker image.

* add missing colon.

* add jinja2 to requirements for dep-api-op.

* update chart versions.

* format python code with black.

* fix internal CANVAS_INFO_ENDPOINT from https to http.

* add Service-Inventory ID to PrinterColumns in DependentAPI CRD.

* add age to display columns.

* log service inventory ids on info level.

* replace urls to ihc-dt cluster with localhost.

* update oda-crds chart version.

* Documentation added How-To define unit tests.

* add image for unit test report with failed tests.

* Change Canvas Info Endpoint to http://info.service.cluster.local
(without path)

* format with black.

* remove prerelease suffixes.

---------

Co-authored-by: Ferenc Hechler <ferenc.hechler@telekom.de>

diff --git a/.github/workflows/dockerbuild-prerelease-compcrdwebhook.yml b/.github/workflows/dockerbuild-prerelease-compcrdwebhook.yml
--- a/.github/workflows/dockerbuild-prerelease-compcrdwebhook.yml
+++ b/.github/workflows/dockerbuild-prerelease-compcrdwebhook.yml
@@ -49,6 +49,12 @@ jobs:
           else
               echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
+
+      - name: read release versionnumber of compcrdwebhook from values.yaml
+        id: get_values_release_version
+        uses: mikefarah/yq@master
+        with:
+          cmd: yq '.oda-webhook.version' charts/canvas-oda/values.yaml
               
       - name: Get Git commit timestamps
         run: |
@@ -61,9 +67,20 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Check that release image (after removing prereleasesuffix) does not yet exist 
+        id: check_release_docker_image
+        uses: KerberosMorphy/docker-exist-action@v1.1.1
+        with:
+          registry: docker.io
+          image: ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_release_version.outputs.result }}
+      - name: error if release tag (without prerelease suffix) already exists
+        if: steps.check_release_docker_image.outputs.image_exist==1
+        run: |
+          echo  "::error::image tag ${{ steps.get_values_release_version.outputs.result }} already exists in repo ${{ steps.get_values_image.outputs.result }}, exiting!" && exit 2
                 
       - name: Build and push
-        uses: docker/build-push-action@v5
+        uses: docker/build-push-action@v6
         with:
           context: source/webhooks
           file: source/webhooks/webhook-dockerfile
diff --git a/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml b/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml
--- a/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml
+++ b/.github/workflows/dockerbuild-prerelease-dependentapi-simple-operator.yml
@@ -48,6 +48,12 @@ jobs:
           else
               echo "::error::Version ${{ steps.get_values_version.outputs.result }} does not match prerelease format <n>.<n>.<n>-<prerelease>" && exit 1
           fi        
+
+      - name: read release versionnumber of dependentapi-simple-operator from values.yaml
+        id: get_values_release_version
+        uses: mikefarah/yq@master
+        with:
+          cmd: yq '.dependentapi-simple-operator.version' charts/canvas-oda/values.yaml
               
       - name: Get Git commit timestamps
         run: |
@@ -60,9 +66,61 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Check that release image (after removing prereleasesuffix) does not yet exist 
+        id: check_release_docker_image
+        uses: KerberosMorphy/docker-exist-action@v1.1.1
+        with:
+          registry: docker.io
+          image: ${{ steps.get_values_image.outputs.result }}:${{ steps.get_values_release_version.outputs.result }}
+      - name: error if release tag (without prerelease suffix) already exists
+        if: steps.check_release_docker_image.outputs.image_exist==1
+        run: |
+          echo  "::error::image tag ${{ steps.get_values_release_version.outputs.result }} already exists in repo ${{ steps.get_values_image.outputs.result }}, exiting!" && exit 2
+      - name: Build and export to Docker
+        uses: docker/build-push-action@v6
+        with:
+          context: source/operators/dependentApiSimpleOperator/docker
+          build-args: |
+            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
+            GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
+            CICD_BUILD_TIME=${{ env.CICD_BUILD_TIME }}
+          load: true
+          push: true
+          tags: |
+            ${{ steps.get_values_image.outputs.result }}:latest
+        env:
+          SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
+      
+      # test
+      # problem using local image: https://github.com/docker/build-push-action/issues/1015
+      - name: Run Unit Tests
+        uses: docker/build-push-action@v6
+        with:
+          context: source/operators/dependentApiSimpleOperator/docker
+          file: source/operators/dependentApiSimpleOperator/docker/DockerfileTest
+          build-args: |
+            FROM_IMAGE=${{ steps.get_values_image.outputs.result }}:latest
+          load: true
+          push: false
+          tags: local-test-img
+      
+      - name: Get Test Results
+        run: |
+          docker run --rm local-test-img > junit-report.xml
+          cat junit-report.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        #if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'junit-report.xml'
+          fail_on_failure: true
+          include_passed: true
+          detailed_summary: true
                 
       - name: Build and push
-        uses: docker/build-push-action@v5
+        uses: docker/build-push-action@v6
         with:
           context: source/operators/dependentApiSimpleOperator/docker
           build-args: |
