Automate Docker Build: skip tests in step 5 'remove prerelease suffixes' (#313)
* Automate Docker Build: skip tests in step 5 'remove prerelease
suffixes'.

* [skip tests] set prerelease version for testing.

* avoid check failing, when grep does not find any matches.

* [skip tests] write message, if tests are not skiped due to changes to
other files.

* remove prerelease suffixes (step 5).

* remove leftover space from testing

---------

Co-authored-by: Ferenc Hechler <ferenc.hechler@telekom.de>

diff --git a/.github/workflows/trigger_tests.yml b/.github/workflows/trigger_tests.yml
--- a/.github/workflows/trigger_tests.yml
+++ b/.github/workflows/trigger_tests.yml
@@ -12,13 +12,17 @@ jobs:
     runs-on: ubuntu-latest
     if: "!contains(github.event.pull_request.title, '[skip tests]')"
     outputs:
-      SKIPTESTS: ${{ steps.check_skiptests_msg.outputs.SKIPTESTS }}
+      COMMITMSG_SKIPTESTS: ${{ steps.check_skiptests_msg.outputs.SKIPTESTS }}
+      PRERELEASESUFFIX_SKIPTESTS: ${{ steps.check_prereleasesuffixremoval.outputs.SKIPTESTS }}
     steps:
+    
     - name: Checkout code
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
       with:
         ref: ${{ github.event.pull_request.head.ref }}
         repository: ${{ github.event.pull_request.head.repo.full_name }}
+        fetch-depth: 2    # this is needed for getting the diff of the last commit
+        
     - name: Check for [skip tests] in Message
       id: check_skiptests_msg
       run: |
@@ -29,19 +33,67 @@ jobs:
           echo "SKIPPING TESTS"
           echo "SKIPTESTS=1" >> $GITHUB_OUTPUT
         else
-          echo "EXECUTING TESTS"
-          echo "SKIPTESTS=" >> $GITHUB_OUTPUT
+          echo "'[skip tests]' magic words were not found in commit message, not skipping tests"
         fi
+
+    - name: check last commit contains only prerelease suffix removals 
+      id: check_prereleasesuffixremoval
+      shell: bash
+      run: |
+        echo "---- CHANGED FILES ----"
+        git diff --name-only HEAD~1
+        echo "---- ------------- ----"
+        export CHANGED_FILES=$(git diff --name-only HEAD~1)
+        if [ "$CHANGED_FILES" == "charts/canvas-oda/values.yaml" ]
+        then
+          echo "only charts/canvas-oda/values.yaml was changed."
+          echo "checking changes if only prerelease suffixes were removed."
+          
+          echo "---- DIFF FROM LAST COMMIT ----"
+          git diff -w -U0 --color=always HEAD~1
+          echo "---- --------------------- ----"
+          
+          git diff -w -U0 --color=never HEAD~1 > gitdiff.txt
+          export OLD_LINES=$(cat gitdiff.txt | grep -i "^- " | wc -l)
+          export NEW_LINES=$(cat gitdiff.txt | grep -i "^+ " | wc -l)
+          export NEW_LINES_WITH_EMPTY_PRS=$(cat gitdiff.txt | grep -i "^+ .*prereleasesuffix:\s*$" | wc -l)
+
+          echo "OLD LINES ($OLD_LINES)"
+          cat gitdiff.txt | grep -i "^- " || true
+          echo "---- -------------------- ----"
+          echo "NEW LINES ($NEW_LINES)"
+          cat gitdiff.txt | grep -i "^+ " || true
+          echo "---- -------------------- ----"
+          echo "NEW LINES WITH EMPTY PRERELEASESUFFIX ($NEW_LINES_WITH_EMPTY_PRS)"
+          cat gitdiff.txt | grep -i "^+ .*prereleasesuffix:\s*$" || true
+          echo "---- -------------------- ----"
+          
+          if [ "$OLD_LINES" != "$NEW_LINES" ]
+          then
+            echo "Number of old lines and new lines differs, not skipping tests"
+          else
+            if [ "$NEW_LINES" != "$NEW_LINES_WITH_EMPTY_PRS" ]
+            then
+              echo "not all new lines are empty prereleasesuffixes, not skipping tests"
+            else
+              echo "detected only prerelease suffix removals in changed files"
+              echo "SKIPPING TESTS"
+              echo "SKIPTESTS=1" >> $GITHUB_OUTPUT
+            fi
+          fi
+        else
+          echo "changes to other files than values.yaml detected, not skipping tests"
+        fi 
 
 
   run_tests_job:
     runs-on: ubuntu-latest
     needs: check_skip_tests_job    
-    if: "!needs.check_skip_tests_job.outputs.SKIPTESTS"
+    if: "!needs.check_skip_tests_job.outputs.COMMITMSG_SKIPTESTS && !needs.check_skip_tests_job.outputs.PRERELEASESUFFIX_SKIPTESTS"
 
     steps:
     - name: Checkout code
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
       with:
         ref: ${{ github.event.pull_request.head.ref }}
         repository: ${{ github.event.pull_request.head.repo.full_name }}
